name: aha
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - attrs=21.4.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.4=py38hce1f21e_0
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.14.12=h8948797_3
  - certifi=2021.10.8=py38h578d9bd_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=he6710b0_3
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=habf39ab_1
  - kiwisolver=1.3.1=py38h1fd1430_1
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libllvm11=11.1.0=hf817b99_2
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.38.0=py38h4ff587b_0
  - lz4-c=1.9.2=heb0550a_3
  - matplotlib=3.4.3=py38h578d9bd_1
  - matplotlib-base=3.4.3=py38hbbc1b5f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h7f8727e_2
  - networkx=2.7.1=pyhd3eb1b0_0
  - numba=0.55.1=py38h51133e4_0
  - numexpr=2.8.1=py38h6abb31d_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1o=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py38h295c915_1
  - pango=1.42.4=h049681c_0
  - pcre=8.44=he6710b0_0
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=21.2.4=py38h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - pluggy=1.0.0=py38h06a4308_0
  - py=1.10.0=pyhd3eb1b0_0
  - pydot=1.4.1=py38_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pytest=6.2.5=py38h06a4308_2
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-graphviz=0.16=pyhd3eb1b0_1
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - scipy=1.7.3=py38hc147768_0
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_0
  - sparse=0.13.0=pyhd8ed1ab_0
  - sqlite=3.37.0=hc218d9a_0
  - tbb=2021.5.0=hd09550d_0
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py38h497a2fe_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - pycodestyle==2.8.0
    - pytest-repeat==0.9.1
prefix: /home/oliviahsu/miniconda3/envs/aha
